import { ICitybikModuleName } from './_citybikInterfaces';

export const ModuleName: ICitybikModuleName = 'citybik';

export const SET_CITYBIK_NETWORKS_LIST = 'module/citybik/SET_CITYBIK_NETWORKS_LIST';
export const SET_CURRENT_CITYBIK_NETWORK = 'module/citybik/SET_CURRENT_CITYBIK_NETWORK';
export const CURRENT_CITYBIK_NETWORK_LOADING_STATUS_LOADING = 'module/citybik/CURRENT_CITYBIK_NETWORK_LOADING_STATUS_LOADING';
export const CURRENT_CITYBIK_NETWORK_LOADING_STATUS_DONE = 'module/citybik/CURRENT_CITYBIK_NETWORK_LOADING_STATUS_DONE';
export const CURRENT_CITYBIK_NETWORK_LOADING_STATUS_ERROR = 'module/citybik/CURRENT_CITYBIK_NETWORK_LOADING_STATUS_ERROR';
export const CURRENT_CITYBIK_NETWORK_LOADING_STATUS_UNCAUGHT = 'module/citybik/CURRENT_CITYBIK_NETWORK_LOADING_STATUS_UNCAUGHT';
export const CITYBIK_NETWORKS_LOADING_STATUS_LOADING = 'module/citybik/CITYBIK_NETWORKS_LOADING_STATUS_LOADING';
export const CITYBIK_NETWORKS_LOADING_STATUS_DONE = 'module/citybik/CITYBIK_NETWORKS_LOADING_STATUS_DONE';
export const CITYBIK_NETWORKS_LOADING_STATUS_ERROR = 'module/citybik/CITYBIK_NETWORKS_LOADING_STATUS_ERROR';
export const CITYBIK_NETWORKS_LOADING_STATUS_UNCAUGHT = 'module/citybik/CITYBIK_NETWORKS_LOADING_STATUS_UNCAUGHT';

